/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.io.File;
import java.io.IOException;
import java.io.StringWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author saleh
 */
public class LoginPanel extends javax.swing.JFrame {
public static LoginPanel frame;
public static  Socket s;
public static  SocketToServer ss = new SocketToServer();
public static String ipp="192.168.43.20";
public static int portt=1994;
 

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        System.setProperty("javax.net.ssl.trustStore","encrypted.store");
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        jPanellSignin = new javax.swing.JPanel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        LblUsername = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabellogintoyouraccount = new javax.swing.JLabel();
        JPanelLogin = new javax.swing.JPanel();
        LblLogin1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LblSignup = new javax.swing.JLabel();
        jPanellSignup = new javax.swing.JPanel();
        LblRegistration = new javax.swing.JLabel();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jTextFieldUser1 = new javax.swing.JTextField();
        jPassfield = new javax.swing.JPasswordField();
        LblEmail = new javax.swing.JLabel();
        LblPassword1 = new javax.swing.JLabel();
        LblUsername2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LblRegister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanellSignin.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jTextFieldUsername.setToolTipText("");
        jTextFieldUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(50, 183, 226)));

        jPasswordField.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(50, 183, 226)));

        LblUsername.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        LblUsername.setForeground(new java.awt.Color(153, 153, 153));
        LblUsername.setText("Username");

        LblPassword.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(153, 153, 153));
        LblPassword.setText("Password");

        jPanel1.setBackground(new java.awt.Color(50, 183, 226));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabellogintoyouraccount.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabellogintoyouraccount.setForeground(new java.awt.Color(50, 183, 226));
        jLabellogintoyouraccount.setText("Login To Your Account ");

        JPanelLogin.setBackground(new java.awt.Color(50, 183, 226));

        LblLogin1.setBackground(new java.awt.Color(50, 183, 226));
        LblLogin1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        LblLogin1.setForeground(new java.awt.Color(255, 255, 255));
        LblLogin1.setText("Sign in");
        LblLogin1.setToolTipText("");
        LblLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblLogin1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPanelLoginLayout = new javax.swing.GroupLayout(JPanelLogin);
        JPanelLogin.setLayout(JPanelLoginLayout);
        JPanelLoginLayout.setHorizontalGroup(
            JPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLoginLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LblLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        JPanelLoginLayout.setVerticalGroup(
            JPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLoginLayout.createSequentialGroup()
                .addComponent(LblLogin1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        LblSignup.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        LblSignup.setText("Sign up");
        LblSignup.setToolTipText("");
        LblSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblSignupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(LblSignup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblSignup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanellSigninLayout = new javax.swing.GroupLayout(jPanellSignin);
        jPanellSignin.setLayout(jPanellSigninLayout);
        jPanellSigninLayout.setHorizontalGroup(
            jPanellSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellSigninLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabellogintoyouraccount)
                .addGap(46, 46, 46))
            .addGroup(jPanellSigninLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellSigninLayout.createSequentialGroup()
                        .addComponent(LblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(144, 144, 144))
                    .addGroup(jPanellSigninLayout.createSequentialGroup()
                        .addComponent(LblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(149, 149, 149))
                    .addComponent(jPasswordField)
                    .addComponent(jTextFieldUsername))
                .addContainerGap())
            .addGroup(jPanellSigninLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(JPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanellSigninLayout.setVerticalGroup(
            jPanellSigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanellSigninLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabellogintoyouraccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(JPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelSlider1.add(jPanellSignin, "card2");

        jPanellSignup.setBackground(new java.awt.Color(255, 255, 255));

        LblRegistration.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        LblRegistration.setForeground(new java.awt.Color(50, 183, 226));
        LblRegistration.setText("Registration...");

        jTextFieldEmail1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jTextFieldEmail1.setToolTipText("");
        jTextFieldEmail1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(50, 183, 226)));

        jTextFieldUser1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jTextFieldUser1.setToolTipText("Username");
        jTextFieldUser1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(50, 183, 226)));
        jTextFieldUser1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUser1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldUser1.setName(""); // NOI18N

        jPassfield.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jPassfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(50, 183, 226)));

        LblEmail.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        LblEmail.setForeground(new java.awt.Color(153, 153, 153));
        LblEmail.setText("Email");
        LblEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LblPassword1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        LblPassword1.setForeground(new java.awt.Color(153, 153, 153));
        LblPassword1.setText("Password");

        LblUsername2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        LblUsername2.setForeground(new java.awt.Color(153, 153, 153));
        LblUsername2.setText("Username");

        jPanel3.setBackground(new java.awt.Color(50, 183, 226));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(50, 183, 226));

        LblRegister.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        LblRegister.setForeground(new java.awt.Color(255, 255, 255));
        LblRegister.setText("Register");
        LblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LblRegister)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblRegister)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanellSignupLayout = new javax.swing.GroupLayout(jPanellSignup);
        jPanellSignup.setLayout(jPanellSignupLayout);
        jPanellSignupLayout.setHorizontalGroup(
            jPanellSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanellSignupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellSignupLayout.createSequentialGroup()
                        .addComponent(LblRegistration)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(jTextFieldUser1)
                    .addComponent(jPassfield)
                    .addComponent(LblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanellSignupLayout.createSequentialGroup()
                        .addComponent(LblPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(127, 127, 127))
                    .addGroup(jPanellSignupLayout.createSequentialGroup()
                        .addComponent(LblUsername2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(124, 124, 124))
                    .addComponent(jTextFieldEmail1))
                .addContainerGap())
            .addGroup(jPanellSignupLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanellSignupLayout.setVerticalGroup(
            jPanellSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellSignupLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(LblRegistration)
                .addGap(60, 60, 60)
                .addComponent(LblUsername2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblEmail)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblPassword1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanelSlider1.add(jPanellSignup, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSignupMouseClicked
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(10,5, jPanellSignup, jPanelSlider1.left);
    }//GEN-LAST:event_LblSignupMouseClicked

    private void LblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblRegisterMouseClicked
       //send Action
        //declaratio
        //get text from textfields
        String username = jTextFieldUser1.getText().toString();
        String email= jTextFieldEmail1.getText().toString();
        String passText = new String(jPassfield.getPassword());
        //check if not empty
        if(!isValidEmailAddress(email)){
            new Response().ErrorRegestration("check ur email",this.jPanellSignup);
        }
        else
       if(!email.equalsIgnoreCase("") && isValidEmailAddress(email) && !username.equalsIgnoreCase("") && !passText.equalsIgnoreCase("") ){ 
           //create json file
           JSONObject obj = new JSONObject();
            obj.put("Action", "Signup");
            obj.put("username", username);
            obj.put("email", email);
            obj.put("password", passText);  
            StringWriter out = new StringWriter();
            try {
                obj.writeJSONString(out);
                //create socket
                s=ss.CreateSocket(ipp,portt);
                if (this.s.isConnected()){System.out.println("Connexion is ready");
                //send json file with socket
     
                ss.send(this.s, String.valueOf(out),this.jPanellSignup,frame);
                jPanelSlider1.nextPanel(20, 20, JPanelLogin, jPanelSlider1.right);
                }
            } catch (IOException ex) {
               ex.printStackTrace();
            }
            
            
        }     
       
    }//GEN-LAST:event_LblRegisterMouseClicked

    private void LblLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblLogin1MouseClicked
        // TODO add your handling code here:
      
       //get text fr&om textfields
        String username = jTextFieldUsername.getText().toString();
        String passText = new String(jPasswordField.getPassword());
        //check if not empty
       if(!username.equalsIgnoreCase("") && !passText.equalsIgnoreCase("") ){ 
           //create json file
           JSONObject obj = new JSONObject();
            obj.put("Action", "SignIn");
            obj.put("username", username);
            obj.put("password", passText);  
            StringWriter out = new StringWriter();
            try {
                obj.writeJSONString(out);
                //create socket
               
                s=ss.CreateSocket(ipp,portt);
                if (s.isConnected()){System.out.println("Connexion is ready");
                
                //send json file with socket
                ss.send(s, String.valueOf(out),this.jPanellSignup,frame);}        
            } catch (IOException ex) {
               ex.printStackTrace();
            }
            if(!this.isVisible()) ss.KillSocket(s);
       }
    }//GEN-LAST:event_LblLogin1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 frame = new LoginPanel();
                //new LoginPanel().setVisible(true);
                frame.setVisible(true);
                
                ClassLoader classLoader = getClass().getClassLoader();
                File file = new File(classLoader.getResource("encrypted.store").getPath());
                System.setProperty("javax.net.ssl.trustStore",file.toString());
             
            }
        });
    }
    public boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelLogin;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblLogin1;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblPassword1;
    private javax.swing.JLabel LblRegister;
    private javax.swing.JLabel LblRegistration;
    private javax.swing.JLabel LblSignup;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JLabel LblUsername2;
    private javax.swing.JLabel jLabellogintoyouraccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JPanel jPanellSignin;
    private javax.swing.JPanel jPanellSignup;
    private javax.swing.JPasswordField jPassfield;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldUser1;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
